import uuid
import json
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

from signals import groq_signal, stylometric_signal

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# -------------------------
# Audit Log Helper
# -------------------------

LOG_PATH = "audit_log.jsonl"

def log_event(entry):
    entry["timestamp"] = datetime.now(timezone.utc).isoformat()
    with open(LOG_PATH, "a") as f:
        f.write(json.dumps(entry) + "\n")

def read_log(limit=20):
    try:
        with open(LOG_PATH) as f:
            lines = f.readlines()
    except FileNotFoundError:
        return []
    return [json.loads(line) for line in lines[-limit:]]

# -------------------------
# Classification Helpers
# -------------------------

# The three transparency-label variants, verbatim from planning.md
# (Transparency Label Design section).
LABEL_AI = {
    "label": "Likely AI-Generated",
    "label_detail": (
        "Our system found strong evidence that this content was generated by "
        "artificial intelligence. Confidence: High."
    ),
}
LABEL_HUMAN = {
    "label": "Likely Human-Written",
    "label_detail": (
        "Our system found strong evidence that this content was written by a "
        "human author. Confidence: High."
    ),
}
LABEL_UNCERTAIN = {
    "label": "Uncertain Result",
    "label_detail": (
        "Our system could not confidently determine whether this content was "
        "AI-generated or human-written. This result should not be considered "
        "definitive and may require human review."
    ),
}


def generate_label(confidence):
    """Map a confidence score (0.0 human .. 1.0 AI) to the transparency label.

    Returns the full label variant (title + detail) so the text shown to the
    user changes with the score. The three variants are the ones designed in
    planning.md. Returns: dict with "label" and "label_detail".
    """
    if confidence <= 0.45:
        return LABEL_HUMAN
    if confidence <= 0.54:
        return LABEL_UNCERTAIN
    return LABEL_AI


def classify(confidence):
    """Map a confidence score (0.0 human .. 1.0 AI) to an attribution and label.

    Mirrors the Uncertainty Representation table in planning.md. The attribution
    has five levels; the transparency label collapses to the three variants
    returned by generate_label().
    """
    if confidence <= 0.25:
        attribution = "human"
    elif confidence <= 0.45:
        attribution = "likely_human"
    elif confidence <= 0.54:
        attribution = "uncertain"
    elif confidence <= 0.75:
        attribution = "likely_ai"
    else:
        attribution = "ai"
    return attribution, generate_label(confidence)

# -------------------------
# Routes
# -------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(silent=True) or {}
    text = data.get("text")
    creator_id = data.get("creator_id")

    # Validate the request.
    if not text or not isinstance(text, str) or not text.strip():
        return jsonify({"error": "Field 'text' is required and must be a non-empty string."}), 400
    if not creator_id or not isinstance(creator_id, str):
        return jsonify({"error": "Field 'creator_id' is required and must be a string."}), 400

    content_id = str(uuid.uuid4())

    # Signal 1 — Groq LLM.
    signal_1 = groq_signal(text)
    llm_score = signal_1["score"]

    # Signal 2 — Stylometric Analysis.
    signal_2 = stylometric_signal(text)
    stylometric_score = signal_2["score"]

    # Confidence scoring: both signals contribute equally (see planning.md).
    confidence = round((llm_score + stylometric_score) / 2, 4)
    attribution, label = classify(confidence)

    # Write a structured entry to the audit log, capturing both signal scores.
    log_event({
        "event": "classification",
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "label": label["label"],
        "status": "classified",
        "appeal_filed": False,
    })

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label["label"],
        "label_detail": label["label_detail"],
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
    })


def find_classification(content_id):
    """Return the original classification log entry for content_id, or None."""
    for entry in reversed(read_log(limit=10000)):
        if entry.get("content_id") == content_id and entry.get("event") == "classification":
            return entry
    return None


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(silent=True) or {}
    content_id = data.get("content_id")
    reasoning = data.get("creator_reasoning")

    # Validate the request.
    if not content_id or not isinstance(content_id, str):
        return jsonify({"error": "Field 'content_id' is required and must be a string."}), 400
    if not reasoning or not isinstance(reasoning, str) or not reasoning.strip():
        return jsonify({"error": "Field 'creator_reasoning' is required and must be a non-empty string."}), 400

    # Verify the submission exists before accepting the appeal.
    original = find_classification(content_id)
    if original is None:
        return jsonify({"error": f"No submission found for content_id '{content_id}'."}), 404

    # Log the appeal alongside the original classification decision, including the
    # creator's reasoning so a reviewer has full context.
    log_event({
        "event": "appeal",
        "content_id": content_id,
        "creator_id": original.get("creator_id"),
        "attribution": original.get("attribution"),
        "confidence": original.get("confidence"),
        "llm_score": original.get("llm_score"),
        "stylometric_score": original.get("stylometric_score"),
        "label": original.get("label"),
        "appeal_reasoning": reasoning,
        "appeal_filed": True,
        "status": "under_review",
    })

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal was received and is under review.",
    })


@app.route("/log", methods=["GET"])
def view_log():
    return jsonify({
        "entries": read_log()
    })


if __name__ == "__main__":
    app.run(port=5000, debug=True)