"""Detection signals for Provenance Guard.

Each signal returns a normalized score between 0.0 and 1.0:
    0.0 = Strongly Human
    1.0 = Strongly AI
"""

import os
import re
import json

from groq import Groq
from dotenv import load_dotenv

load_dotenv()

GROQ_MODEL = "llama-3.3-70b-versatile"

_client = None


def _get_client():
    """Lazily create the Groq client so importing this module never crashes."""
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


SYSTEM_PROMPT = (
    "You are an AI-text detection assistant. You evaluate a piece of writing "
    "and estimate the probability that it was generated by a large language "
    "model rather than written by a human.\n\n"
    "Consider: overall writing style, sentence coherence, vocabulary and word "
    "choice, consistency of tone, and common AI writing patterns (overly even "
    "rhythm, generic phrasing, hedging, lack of specific lived detail).\n\n"
    "Respond ONLY with a JSON object of the form:\n"
    '{"score": <float 0.0-1.0>, "reasoning": "<one short sentence>"}\n'
    "where 0.0 means strongly human and 1.0 means strongly AI."
)


def groq_signal(text):
    """Signal 1 — Groq LLM.

    Sends `text` to the Groq API and returns a float score in [0.0, 1.0]
    representing how likely the text is AI-generated.

    Returns:
        dict: {"score": float, "reasoning": str}
    """
    client = _get_client()

    response = client.chat.completions.create(
        model=GROQ_MODEL,
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Analyze this text:\n\n{text}"},
        ],
    )

    raw = response.choices[0].message.content
    data = json.loads(raw)

    # Clamp defensively to the documented range.
    score = float(data.get("score", 0.5))
    score = max(0.0, min(1.0, score))

    return {
        "score": score,
        "reasoning": data.get("reasoning", ""),
    }


# -------------------------
# Signal 2 — Stylometric Analysis
# -------------------------

def _clamp01(x):
    return max(0.0, min(1.0, x))

def _split_sentences(text):
    parts = re.split(r"[.!?]+", text)
    return [p.strip() for p in parts if p.strip()]

def _tokenize_words(text):
    return re.findall(r"[a-zA-Z']+", text.lower())


def stylometric_signal(text):
    """Signal 2 — Stylometric Analysis.

    Computes three measurable writing statistics, normalizes each to [0.0, 1.0]
    where higher = more AI-like, and returns their average.

    Returns:
        dict: {"score": float, "metrics": {...}}
    """
    sentences = _split_sentences(text)
    words = _tokenize_words(text)
    num_words = len(words)

    # --- Metric 1: Sentence length variance ---
    # Human writing varies sentence length; AI tends to be uniform.
    # Low variance -> AI-like (score near 1). High variance -> human (near 0).
    sentence_lengths = [len(_tokenize_words(s)) for s in sentences]
    if len(sentence_lengths) >= 2:
        mean_len = sum(sentence_lengths) / len(sentence_lengths)
        variance = sum((l - mean_len) ** 2 for l in sentence_lengths) / len(sentence_lengths)
        std_dev = variance ** 0.5
        # std_dev <= 3 words (very uniform) -> 1.0 AI ; >= 9 words (very varied) -> 0.0 human
        variance_score = _clamp01((9.0 - std_dev) / 6.0)
    else:
        # Too few sentences to judge -> neutral.
        variance_score = 0.5

    # --- Metric 2: Type-Token Ratio (vocabulary diversity) ---
    # Human writing is more lexically varied (high TTR); AI repeats (low TTR).
    # TTR is length-sensitive, so we measure over the first 100 words.
    if num_words > 0:
        window = words[:100]
        ttr = len(set(window)) / len(window)
        # TTR >= 0.90 (diverse) -> 0.0 human ; TTR <= 0.70 (repetitive) -> 1.0 AI.
        # NOTE: at short lengths TTR is naturally high (~0.85-0.90), so this
        # metric is a weak discriminator on its own — see planning.md limitations.
        ttr_score = _clamp01((0.90 - ttr) / (0.90 - 0.70))
    else:
        ttr_score = 0.5

    # --- Metric 3: Punctuation frequency ---
    # Casual human writing is often punctuation-sparse OR irregular; polished AI
    # prose uses steady, "correct" punctuation. We treat a moderate, even rate
    # of structural punctuation as more AI-like.
    if num_words > 0:
        punct_count = len(re.findall(r"[,;:]", text))
        punct_rate = punct_count / num_words
        # Steady structural punctuation reads as polished/AI-like.
        # rate 0 -> 0.0 human ; rate >= 0.08 (frequent commas/clauses) -> 1.0 AI.
        punct_score = _clamp01(punct_rate / 0.08)
    else:
        punct_score = 0.5

    score = (variance_score + ttr_score + punct_score) / 3.0

    return {
        "score": round(score, 4),
        "metrics": {
            "sentence_length_variance": round(variance_score, 4),
            "type_token_ratio": round(ttr_score, 4),
            "punctuation_frequency": round(punct_score, 4),
        },
    }


if __name__ == "__main__":
    # Independent test harness — run `python signals.py` to inspect output.
    samples = {
        "clearly_ai": (
            "Artificial intelligence represents a transformative paradigm shift "
            "in modern society. It is important to note that while the benefits "
            "of AI are numerous, it is equally essential to consider the ethical "
            "implications. Furthermore, stakeholders across various sectors must "
            "collaborate to ensure responsible deployment."
        ),
        "clearly_human": (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium "
            "in it and i was thirsty for like three hours after. my friend got "
            "the spicy version and said it was better. probably won't go back "
            "unless someone drags me there"
        ),
        "borderline_formal_human": (
            "The relationship between monetary policy and asset price inflation "
            "has been extensively studied in the literature. Central banks face "
            "a fundamental tension between their mandate for price stability and "
            "the unintended consequences of prolonged low interest rates on "
            "equity and real estate valuations."
        ),
        "borderline_edited_ai": (
            "I've been thinking a lot about remote work lately. There are "
            "genuine tradeoffs — flexibility and no commute on one side, "
            "isolation and blurred work-life boundaries on the other. Studies "
            "show productivity varies widely by individual and role type."
        ),
    }

    for name, text in samples.items():
        g = groq_signal(text)
        s = stylometric_signal(text)
        combined = round((g["score"] + s["score"]) / 2, 4)
        print(f"\n[{name}]")
        print(f"  groq        = {g['score']}")
        print(f"  stylometric = {s['score']}  {s['metrics']}")
        print(f"  combined    = {combined}")
